### ISSUE TITLE
Should we support two spindle types in one run?

### ISSUE THREAD

**Issue by jens-k** [medpsytuebingen/Matlab#12]
Fast and slow spindles with a minimal distance between their frequency peaks? Or should we let the user deal with that, e.g. by having them call the function twice?

**Comment by NNiethard** [comment]
originally I also had this in mind but automatic definition of the two spindle bands is not trivial if we still want to use indiv spindle bands (at least for rodent data).

**Comment by jens-k** [comment]
We decided this should be left to the user.
