### ISSUE TITLE
Fs not integer?

### ISSUE THREAD

**Issue by jens-k** [medpsytuebingen/Matlab#13]
https://github.com/medpsytuebingen/Matlab/blob/802419628ebb5a023dcc4f7be5c8269457bdb66b/event_detector/detectEvents.m#L712

What does it mean for the sampling frequency to be non-integer?

**Comment by NNiethard** [comment]
I had a case with non integer sampling frequency. However this turned out to be a bug by importing neuralynx data into spike 2.
Probably we should include a warning if this is the case.

**Comment by jens-k** [comment]
Or an error, right? Why would one sample e.g., 1000.2 samples a second? That is so unlikely that I guess in almost all cases something went wrong somewhere.

**Comment by jens-k** [comment]
https://github.com/medpsytuebingen/Matlab/blob/384bfd77ecd69415340a3177e7c29cd1f5953c90/event_detector/detectEvents.m#L130
