### ISSUE TITLE
Problem in ripple detection

### ISSUE THREAD

**Issue by jens-k** [medpsytuebingen/Matlab#15]
https://github.com/medpsytuebingen/Matlab/blob/802419628ebb5a023dcc4f7be5c8269457bdb66b/event_detector/detectEvents.m#L925

Not sure what's happening here. If the control channel is not in the data, delete this particular ripple? 

Also, should the control channel really be given as .cfg.rip_control_Chan.label? Why not cfg.rip_control_chan? What happens if no control channel is provided?

**Comment by NNiethard** [comment]
It will delete the detected ripple if the current channel is the control channel.
If no control channel is provided no ripple will be detected as a fals positive and all of the previously detected ar ekept as the final ones.
A more flexible inplementation of the control channel that also allows to use previously detected events is on my agenda
